### ISSUE TITLE
Doesn't work recursively

### ISSUE THREAD

**Issue by realh** [WebReflection/gjs-require#1]
This wasn't working for me with code generated by tsc. I think the problem is that the use of global/`window.` exports breaks when `require` is called recursively. The function replaces `window.exports` with a new empty object, orphaning the old one. So when a module writes to `exports` as a global it merges its own exports with those of its last required child, and when the parent module returns, those exports get ignored and `require` returns its local `exports` for that stack frame, which is typically empty.

I modified `require` to save and restore `window.exports` and `window.module` before and after running the required module respectively, and this seemed to fix the problem. Would you like a PR?

**Comment by WebReflection** [comment]
do you have a minimal test to reproduce the issue you are talking about?

in any case, PR welcome, yes.

**Comment by realh** [comment]
I've made 2 PRs. The other PR updates the test to demonstrate the bug in the old version while it passes with the 'fix' applied.

**Comment by WebReflection** [comment]
published as 0.3, thanks 👋
